version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=verysecretadminpass
      - MONGO_INITDB_DATABASE=admin
    volumes: 
      - mongodbdata:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo mongo:27017/test
      start_period: 40s
      interval: 10s
      timeout: 3s
      retries: 3
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_URL=mongodb://db
      - DB_NAME=disguisedcats
      - DB_USER=disguisedcat
      - DB_PASSWORD=123456
      - HOSTNAME=example.loc
      - PORT=9999
      - STATIC_PATH=/var/static
      - DEBUG=True
    volumes:
      - appstatic:/var/static
    depends_on:
      - db
        # condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      start_period: 5s
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  mongodbdata:
    driver: local
  appstatic:
    driver: local
